// web/src/components/layout/TopNavigation.vue
<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Search, ArrowDown, User, SwitchButton } from '@element-plus/icons-vue'
import AppAvatar from '@/components/AppAvatar.vue'
import { getUser, isLoggedIn, clearAuth } from '@/utils/auth'
import { logout as logoutApi } from '@/api/user'

const emit = defineEmits(['logout'])
const router = useRouter()
const route = useRoute()

const searchQuery = ref('')
const showMenu = ref(false)
const loggedIn = ref(isLoggedIn())
const user = ref(getUser())

const navItems = [
  { path: '/', label: '首页' },
  { path: '/live', label: '直播' },
  { path: '/subscribe', label: '订阅' }
]

const displayName = computed(() => user.value?.nickname || user.value?.username || '')

onMounted(refreshAuth)
watch(() => route.path, refreshAuth)

function refreshAuth() {
  loggedIn.value = isLoggedIn()
  user.value = getUser()
}

function isActive(path) {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}

function onSearch() {
  const q = searchQuery.value.trim()
  if (!q) return
  router.push({ path: '/search', query: { keyword: q } })
}

async function onLogout() {
  showMenu.value = false
  try {
    if (loggedIn.value) await logoutApi()
  } catch {
    /* ignore */
  }
  clearAuth()
  refreshAuth()
  emit('logout')
  router.push('/')
}
</script>

<template>
  <header class="top-nav">
    <div class="inner">
      <router-link to="/" class="logo">
        <span class="logo-icon">D</span>
        <span class="logo-text">doinb</span>
      </router-link>

      <nav class="nav-links">
        <router-link
          v-for="item in navItems"
          :key="item.path"
          :to="item.path"
          class="nav-link"
          :class="{ active: isActive(item.path) }"
        >
          {{ item.label }}
        </router-link>
      </nav>

      <form class="search-form" @submit.prevent="onSearch">
        <el-input
          v-model="searchQuery"
          placeholder="搜索视频、直播、用户"
          clearable
          class="search-input"
        />
        <button type="submit" class="search-btn" aria-label="搜索">
          <el-icon><Search /></el-icon>
        </button>
      </form>

      <div v-if="loggedIn && user" class="user-area">
        <button type="button" class="user-trigger" @click="showMenu = !showMenu">
          <AppAvatar :size="32" :src="user.avatar" :name="displayName" />
          <span class="user-name">{{ displayName }}</span>
          <el-icon><ArrowDown /></el-icon>
        </button>
        <div v-if="showMenu" class="menu-backdrop" @click="showMenu = false" />
        <div v-if="showMenu" class="dropdown">
          <router-link to="/profile" class="menu-item" @click="showMenu = false">
            <el-icon><User /></el-icon>
            个人中心
          </router-link>
          <button type="button" class="menu-item menu-item--danger" @click="onLogout">
            <el-icon><SwitchButton /></el-icon>
            退出登录
          </button>
        </div>
      </div>
      <div v-else class="auth-btns">
        <router-link to="/login">
          <el-button text>登录</el-button>
        </router-link>
        <router-link to="/register">
          <el-button type="primary">注册</el-button>
        </router-link>
      </div>
    </div>
  </header>
</template>

<style scoped>
.top-nav {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: var(--doinb-header-height);
  background: #fff;
  border-bottom: 1px solid var(--doinb-border-light);
  z-index: 100;
}

.inner {
  max-width: var(--doinb-content-max);
  margin: 0 auto;
  height: 100%;
  padding: 0 16px;
  display: flex;
  align-items: center;
  gap: 24px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

.logo-icon {
  width: 32px;
  height: 32px;
  background: var(--doinb-primary);
  color: #fff;
  border-radius: var(--doinb-radius-sm);
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 18px;
}

.logo-text {
  font-size: 20px;
  font-weight: 700;
  color: var(--doinb-text-primary);
}

.nav-links {
  display: flex;
  gap: 24px;
  flex-shrink: 0;
}

.nav-link {
  font-size: 15px;
  color: var(--doinb-text-regular);
  transition: color 0.2s;
}

.nav-link:hover,
.nav-link.active {
  color: var(--doinb-primary);
  font-weight: 500;
}

.search-form {
  flex: 1;
  max-width: 400px;
  position: relative;
  display: flex;
  align-items: center;
}

.search-input {
  width: 100%;
}

.search-btn {
  position: absolute;
  right: 8px;
  background: none;
  border: none;
  cursor: pointer;
  color: var(--doinb-text-secondary);
  display: flex;
  padding: 4px;
}

.search-btn:hover {
  color: var(--doinb-primary);
}

.user-area {
  position: relative;
  flex-shrink: 0;
}

.user-trigger {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border: none;
  background: none;
  border-radius: var(--doinb-radius-sm);
  cursor: pointer;
  transition: background 0.2s;
}

.user-trigger:hover {
  background: var(--doinb-bg-page);
}

.user-name {
  font-size: 14px;
  color: var(--doinb-text-regular);
  max-width: 100px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.menu-backdrop {
  position: fixed;
  inset: 0;
  z-index: 101;
}

.dropdown {
  position: absolute;
  right: 0;
  top: calc(100% + 8px);
  width: 160px;
  background: #fff;
  border: 1px solid var(--doinb-border-light);
  border-radius: var(--doinb-radius-sm);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  z-index: 102;
  overflow: hidden;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 12px 16px;
  font-size: 14px;
  color: var(--doinb-text-regular);
  background: none;
  border: none;
  cursor: pointer;
  text-align: left;
  transition: background 0.2s;
}

.menu-item:hover {
  background: var(--doinb-bg-page);
}

.menu-item--danger {
  border-top: 1px solid var(--doinb-border-light);
}

.auth-btns {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

@media (max-width: 768px) {
  .nav-links,
  .user-name {
    display: none;
  }
}
</style>

// static/Web UI Template Design/src/app/components/TopNavigation.tsx
import { useState } from 'react';
import { Link, useLocation } from 'react-router';
import { Search, ChevronDown, User, LogOut } from 'lucide-react';
import { Avatar } from './ui/Avatar';
import { Button } from './ui/Button';
import { Input } from './ui/Input';

interface TopNavigationProps {
  isLoggedIn?: boolean;
  userInfo?: {
    name: string;
    avatar?: string;
  };
  onSearch?: (query: string) => void;
}

export function TopNavigation({ isLoggedIn = false, userInfo, onSearch }: TopNavigationProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [showUserMenu, setShowUserMenu] = useState(false);
  const location = useLocation();

  const navItems = [
    { path: '/home', label: '首页' },
    { path: '/live', label: '直播' },
    { path: '/subscribe', label: '订阅' },
  ];

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim() && onSearch) {
      onSearch(searchQuery);
    }
  };

  return (
    <header className="fixed top-0 left-0 right-0 h-14 bg-white border-b border-[#EBEEF5] z-50">
      <div className="max-w-[1280px] mx-auto h-full px-4 flex items-center justify-between gap-6">
        {/* Logo */}
        <Link to="/home" className="flex items-center gap-2 flex-shrink-0">
          <div className="w-8 h-8 bg-[#409EFF] rounded flex items-center justify-center">
            <span className="text-white font-bold text-lg">D</span>
          </div>
          <span className="text-xl font-bold text-[#303133]">doinb</span>
        </Link>

        {/* Navigation */}
        <nav className="flex items-center gap-8">
          {navItems.map((item) => (
            <Link
              key={item.path}
              to={item.path}
              className={`text-base transition-colors ${
                location.pathname === item.path
                  ? 'text-[#409EFF] font-medium'
                  : 'text-[#606266] hover:text-[#409EFF]'
              }`}
            >
              {item.label}
            </Link>
          ))}
        </nav>

        {/* Search */}
        <form onSubmit={handleSearch} className="flex-1 max-w-md">
          <div className="relative">
            <Input
              type="text"
              placeholder="搜索视频、直播、用户"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pr-10"
            />
            <button
              type="submit"
              className="absolute right-3 top-1/2 -translate-y-1/2 text-[#909399] hover:text-[#409EFF] transition-colors"
            >
              <Search size={18} />
            </button>
          </div>
        </form>

        {/* User Actions */}
        {isLoggedIn && userInfo ? (
          <div className="relative flex-shrink-0">
            <button
              onClick={() => setShowUserMenu(!showUserMenu)}
              className="flex items-center gap-2 hover:bg-[#F5F7FA] px-3 py-2 rounded transition-colors"
            >
              <Avatar size={32} src={userInfo.avatar} name={userInfo.name} />
              <span className="text-sm text-[#606266]">{userInfo.name}</span>
              <ChevronDown size={16} className="text-[#909399]" />
            </button>

            {showUserMenu && (
              <>
                <div
                  className="fixed inset-0 z-40"
                  onClick={() => setShowUserMenu(false)}
                />
                <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-md border border-[#EBEEF5] shadow-lg z-50">
                  <Link
                    to="/profile"
                    className="flex items-center gap-2 px-4 py-3 hover:bg-[#F5F7FA] transition-colors text-[#606266]"
                    onClick={() => setShowUserMenu(false)}
                  >
                    <User size={16} />
                    <span>个人中心</span>
                  </Link>
                  <button
                    className="w-full flex items-center gap-2 px-4 py-3 hover:bg-[#F5F7FA] transition-colors text-[#606266] border-t border-[#EBEEF5]"
                    onClick={() => setShowUserMenu(false)}
                  >
                    <LogOut size={16} />
                    <span>退出登录</span>
                  </button>
                </div>
              </>
            )}
          </div>
        ) : (
          <div className="flex items-center gap-3 flex-shrink-0">
            <Link to="/login">
              <Button variant="text" size="medium">
                登录
              </Button>
            </Link>
            <Link to="/register">
              <Button variant="primary" size="medium">
                注册
              </Button>
            </Link>
          </div>
        )}
      </div>
    </header>
  );
}
