// static/Web UI Template Design/src/app/components/VideoCard.tsx
import { Play, Eye } from 'lucide-react';
import { Link } from 'react-router';
import { Card } from './ui/Card';
import { Avatar } from './ui/Avatar';

export interface VideoCardProps {
  id: string;
  title: string;
  cover: string;
  author: {
    name: string;
    avatar?: string;
  };
  views: number;
  publishedAt: string;
}

export function VideoCard({ id, title, cover, author, views, publishedAt }: VideoCardProps) {
  const formatViews = (num: number) => {
    if (num >= 10000) {
      return `${(num / 10000).toFixed(1)}万`;
    }
    return num.toString();
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) return '今天';
    if (days === 1) return '昨天';
    if (days < 7) return `${days}天前`;
    if (days < 30) return `${Math.floor(days / 7)}周前`;
    if (days < 365) return `${Math.floor(days / 30)}月前`;
    return `${Math.floor(days / 365)}年前`;
  };

  return (
    <Link to={`/video/${id}`}>
      <Card hoverable className="overflow-hidden">
        {/* 封面 16:9 */}
        <div className="relative aspect-video bg-[#F5F7FA] overflow-hidden group">
          <img
            src={cover}
            alt={title}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
          />
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
            <div className="w-12 h-12 rounded-full bg-white/0 group-hover:bg-white/90 flex items-center justify-center transition-all">
              <Play size={24} className="text-white group-hover:text-[#409EFF] fill-current" />
            </div>
          </div>
          {/* 播放次数 */}
          <div className="absolute bottom-2 right-2 px-2 py-1 bg-black/60 rounded text-white text-xs flex items-center gap-1">
            <Eye size={12} />
            <span>{formatViews(views)}</span>
          </div>
        </div>

        {/* 信息 */}
        <div className="p-3">
          <h3 className="text-[#303133] text-sm font-medium line-clamp-2 leading-5 min-h-[2.5rem] mb-2">
            {title}
          </h3>
          <div className="flex items-center gap-2">
            <Avatar size={24} src={author.avatar} name={author.name} />
            <div className="flex-1 flex items-center justify-between text-xs text-[#909399]">
              <span className="truncate">{author.name}</span>
              <span className="flex-shrink-0">{formatDate(publishedAt)}</span>
            </div>
          </div>
        </div>
      </Card>
    </Link>
  );
}

// web/src/components/VideoCard.vue
<script setup>
import { VideoPlay } from '@element-plus/icons-vue'
import AppAvatar from './AppAvatar.vue'
import { resolveMediaUrl } from '@/utils/media'
import { formatRelativeTime } from '@/utils/format'

const props = defineProps({
  id: { type: [Number, String], required: true },
  title: { type: String, required: true },
  coverUrl: { type: String, default: '' },
  authorNickname: { type: String, default: '未知作者' },
  authorAvatar: { type: String, default: '' },
  createTime: { type: String, default: '' }
})

const cover = resolveMediaUrl(props.coverUrl)
</script>

<template>
  <router-link :to="`/video/${id}`" class="video-card">
    <div class="cover-wrap">
      <img v-if="cover" :src="cover" :alt="title" class="cover" />
      <div v-else class="cover cover--placeholder">暂无封面</div>
      <div class="cover-mask">
        <el-icon class="play-icon" :size="28"><VideoPlay /></el-icon>
      </div>
    </div>
    <div class="info">
      <h3 class="title">{{ title }}</h3>
      <div class="meta">
        <AppAvatar :size="24" :src="authorAvatar" :name="authorNickname" />
        <span class="author">{{ authorNickname }}</span>
        <span class="time">{{ formatRelativeTime(createTime) }}</span>
      </div>
    </div>
  </router-link>
</template>

<style scoped>
.video-card {
  display: block;
  background: #fff;
  border-radius: var(--doinb-radius);
  overflow: hidden;
  border: 1px solid var(--doinb-border-light);
  transition: box-shadow 0.2s, transform 0.2s;
}

.video-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  transform: translateY(-2px);
}

.cover-wrap {
  position: relative;
  aspect-ratio: 16 / 9;
  background: var(--doinb-bg-page);
  overflow: hidden;
}

.cover {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s;
}

.video-card:hover .cover {
  transform: scale(1.05);
}

.cover--placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--doinb-text-secondary);
  font-size: 13px;
}

.cover-mask {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0);
  transition: background 0.2s;
}

.video-card:hover .cover-mask {
  background: rgba(0, 0, 0, 0.15);
}

.play-icon {
  color: #fff;
  opacity: 0;
  transition: opacity 0.2s;
}

.video-card:hover .play-icon {
  opacity: 1;
}

.info {
  padding: 12px;
}

.title {
  font-size: 14px;
  font-weight: 500;
  color: var(--doinb-text-primary);
  line-height: 1.4;
  min-height: 2.8em;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  margin-bottom: 8px;
}

.meta {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: var(--doinb-text-secondary);
}

.author {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.time {
  flex-shrink: 0;
}
</style>
